// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/base/base-header.vue')['default']
    BaseIconButton: typeof import('./src/components/base/base-icon-button.vue')['default']
    BaseIconText: typeof import('./src/components/base/base-icon-text.vue')['default']
    BaseImage: typeof import('./src/components/base/base-image.vue')['default']
    BasePagination: typeof import('./src/components/base/base-pagination.vue')['default']
    BaseSearchBar: typeof import('./src/components/base/base-search-bar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheApp: typeof import('./src/components/layouts/the-app.vue')['default']
    TheHeader: typeof import('./src/components/layouts/the-header.vue')['default']
    TheRightAside: typeof import('./src/components/layouts/the-right-aside.vue')['default']
    TheRoot: typeof import('./src/components/base/the-root.vue')['default']
    UerDrawerProfileForm: typeof import('./src/components/modules/user/uer-drawer-profile-form.vue')['default']
    UserDrawer: typeof import('./src/components/modules/user/user-drawer.vue')['default']
    UserDrawerProfile: typeof import('./src/components/modules/user/user-drawer-profile.vue')['default']
    UserDrawerProfileForm: typeof import('./src/components/modules/user/user-drawer-profile-form.vue')['default']
    UserTable: typeof import('./src/components/modules/user/user-table.vue')['default']
  }
}

export {}
